In [1]:
"""
Perform Principal component analysis and perform clustering using first 
3 principal component scores (both heirarchial and k mean clustering(scree plot or elbow curve) and obtain 
optimum number of clusters and check whether we have obtained same number of clusters with the original data 
(class column we have ignored at the begining who shows it has 3 clusters)df

"""

'\nPerform Principal component analysis and perform clustering using first \n3 principal component scores (both heirarchial and k mean clustering(scree plot or elbow curve) and obtain \noptimum number of clusters and check whether we have obtained same number of clusters with the original data \n(class column we have ignored at the begining who shows it has 3 clusters)df\n\n'

In [2]:
import pandas as pd 
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale 

In [3]:
Wine = pd.read_csv('C:/Users/Ashwini/Downloads/wine.csv')
Wine

Type  Alcohol  Malic   Ash  Alcalinity  Magnesium  Phenols  Flavanoids  \
0       1    14.23   1.71  2.43        15.6        127     2.80        3.06   
1       1    13.20   1.78  2.14        11.2        100     2.65        2.76   
2       1    13.16   2.36  2.67        18.6        101     2.80        3.24   
3       1    14.37   1.95  2.50        16.8        113     3.85        3.49   
4       1    13.24   2.59  2.87        21.0        118     2.80        2.69   
..    ...      ...    ...   ...         ...        ...      ...         ...   
173     3    13.71   5.65  2.45        20.5         95     1.68        0.61   
174     3    13.40   3.91  2.48        23.0        102     1.80        0.75   
175     3    13.27   4.28  2.26        20.0        120     1.59        0.69   
176     3    13.17   2.59  2.37        20.0        120     1.65        0.68   
177     3    14.13   4.10  2.74        24.5         96     2.05        0.76   

     Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Proline  
0             0.28             2.29   5.64  1.04      3.92     1065  
1             0.26             1.28   4.38  1.05      3.40     1050  
2             0.30             2.81   5.68  1.03      3.17     1185  
3             0.24             2.18   7.80  0.86      3.45     1480  
4             0.39             1.82   4.32  1.04      2.93      735  
..             ...              ...    ...   ...       ...      ...  
173           0.52             1.06   7.70  0.64      1.74      740  
174           0.43             1.41   7.30  0.70      1.56      750  
175           0.43             1.35  10.20  0.59      1.56      835  
176           0.53             1.46   9.30  0.60      1.62      840  
177           0.56             1.35   9.20  0.61      1.60      560  

[178 rows x 14 columns]

In [4]:
wine = Wine.values
wine

array([[1.000e+00, 1.423e+01, 1.710e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.000e+00, 1.320e+01, 1.780e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.000e+00, 1.316e+01, 2.360e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [3.000e+00, 1.327e+01, 4.280e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [3.000e+00, 1.317e+01, 2.590e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [3.000e+00, 1.413e+01, 4.100e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [5]:
# Normalizing the numerical data 
wine_normal = scale(wine)
wine_normal

array([[-1.21394365,  1.51861254, -0.5622498 , ...,  0.36217728,
         1.84791957,  1.01300893],
       [-1.21394365,  0.24628963, -0.49941338, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [-1.21394365,  0.19687903,  0.02123125, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 1.37386437,  0.33275817,  1.74474449, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 1.37386437,  0.20923168,  0.22769377, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.37386437,  1.39508604,  1.58316512, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [6]:
pca = PCA()
pca_values = pca.fit_transform(wine_normal)

In [7]:
pca_values

array([[-3.52293390e+00, -1.45309844e+00, -1.64795488e-01, ...,
         5.52927766e-01, -3.02978176e-01,  2.00857450e-01],
       [-2.52885806e+00,  3.30019252e-01, -2.02670665e+00, ...,
         3.94971160e-01, -1.46645308e-01,  1.26402355e-01],
       [-2.78502898e+00, -1.03693595e+00,  9.83237703e-01, ...,
         1.89799314e-03,  2.12780166e-02, -5.57515155e-02],
       ...,
       [ 3.02727243e+00, -2.75604024e+00, -9.40803036e-01, ...,
         6.93336340e-01,  1.67035660e-01, -3.16957430e-02],
       [ 2.75522166e+00, -2.29378408e+00, -5.50473677e-01, ...,
         3.44119826e-01, -1.09514873e-01,  1.02823104e-01],
       [ 3.49633565e+00, -2.76060799e+00,  1.01315115e+00, ...,
        -1.89866131e-01, -1.64090011e-01, -2.64916504e-01]])

In [8]:
pca = PCA(n_components = 14)
pca_values = pca.fit_transform(wine_normal)

In [9]:
# The amount of variance that each PCA explains is 
var = pca.explained_variance_ratio_
var

array([0.39542486, 0.17836259, 0.10329102, 0.06627984, 0.06267875,
       0.0480556 , 0.03955707, 0.02500244, 0.02103871, 0.01873615,
       0.01613203, 0.01205691, 0.00925458, 0.00412945])

In [10]:
var1 = np.cumsum(np.round(var,decimals = 4)*100)
var1

array([ 39.54,  57.38,  67.71,  74.34,  80.61,  85.42,  89.38,  91.88,
        93.98,  95.85,  97.46,  98.67,  99.6 , 100.01])

In [11]:
pca = PCA(n_components=3)
principalComponents = pca.fit_transform(wine_normal)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['PC_1','PC_2','PC_3'])

In [12]:
principalDf

PC_1      PC_2      PC_3
0   -3.522934 -1.453098 -0.164795
1   -2.528858  0.330019 -2.026707
2   -2.785029 -1.036936  0.983238
3   -3.922588 -2.768210 -0.174968
4   -1.407511 -0.867773  2.025829
..        ...       ...       ...
173  3.627996 -2.206617 -0.343668
174  2.942729 -1.752263  0.207480
175  3.027272 -2.756040 -0.940803
176  2.755222 -2.293784 -0.550474
177  3.496336 -2.760608  1.013151

[178 rows x 3 columns]

# Hierarchical Clustering

In [ ]:
import scipy.cluster.hierarchy as sch
from sklearn.cluster import AgglomerativeClustering
plt.figure(figsize = (10,6))
dendrogram = sch.dendrogram(sch.linkage(principalDf, method='average'))

In [ ]:
hc = AgglomerativeClustering(n_clusters=6, affinity = 'euclidean', linkage = 'average')
hc

In [ ]:
y_hc = hc.fit_predict(principalDf)

Clusters=pd.DataFrame(y_hc,columns=['Clusters'])

In [ ]:
Clusters.head()

In [ ]:
principalDf['h_clusterid'] = Clusters

In [ ]:
principalDf.sort_values("h_clusterid")

# K Means

In [ ]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 9, random_state = 0)
kmeans.fit(principalDf)

In [ ]:
kmeans.inertia_

In [ ]:
from sklearn.metrics import silhouette_score, calinski_harabasz_score

wcss = []
sil_score = []
cal_haz_score = []

for i in range(1, 11):
    kmeans = KMeans(n_clusters=i,random_state=0)
    kmeans.fit(principalDf)
    wcss.append(kmeans.inertia_)
    if i==1:
        continue #min 2 labels needed for silhoutte and cal_haz score (Refer documentation)
    sil_score.append(silhouette_score(principalDf, kmeans.labels_))
    cal_haz_score.append(calinski_harabasz_score(principalDf, kmeans.labels_))

In [ ]:
plt.plot(range(1, 11), wcss)
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

In [ ]:
kmeans.labels_

In [ ]:
principalDf['clusterid_new'] = kmeans.labels_

In [ ]:
principalDf.sort_values('clusterid_new')

In [ ]:
principalDf['clusterid_new'].value_counts()

# DBSCAN

In [ ]:
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

In [ ]:
array = principalDf.values
array

In [ ]:
dbscan = DBSCAN(eps = 1, min_samples = 3)
dbscan.fit(array)

In [ ]:
dbscan.labels_

In [ ]:
cl = pd.DataFrame(dbscan.labels_, columns=['cluster'])
cl

In [ ]:
clustered = pd.concat([principalDf,cl],axis=1)
clustered